### ISSUE TITLE
Fix MacOS inactive window color

### ISSUE THREAD

**Issue by janodetzel** [nataliefruitema/modern-purple-theme#1]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/33382708/166971058-e0caba95-8853-430b-9980-cc27e31f026c.png">

Hi, I love your theme but really dislike the grey color of the window frame when vscode is not active.
Do you mind to fix this in a future update?

**Comment by nataliefruitema** [comment]
Hi Janodetzel, 

I'm glad to hear that you like the theme and thanks for your suggestion. I've released a new version and changed the color of the title bar when it's not active. Hope you like it :)

**Comment by janodetzel** [comment]
Love it, thank you!
